# Generated by Django 2.2.2 on 2019-07-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100)),
                ('facebook', models.URLField(max_length=1000)),
                ('twitter', models.URLField(max_length=1000)),
                ('instagram', models.URLField(max_length=1000)),
                ('profile', models.ImageField(upload_to='images')),
            ],
        ),
    ]
