# Generated by Django 2.2.2 on 2019-07-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='facebook',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='member',
            name='instagram',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='member',
            name='profile',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='member',
            name='twitter',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
