# Generated by Django 2.2.2 on 2019-07-22 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20190721_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='birthdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
